### ISSUE TITLE
Not working with 0.5.3

### ISSUE THREAD

**Issue by RegProctor** [BiglySoftware/BiglyBT-plugin-3DView#1]
Hi, 

I haven't had 3D Views work yet on my system and when I saw the new 0.5.3 I thought it might start to work but it still hasn't.

I am running opensuse 15.0 and my system in BigBT shows:

> Java 11.0.1 (64 bit)
>   Oracle Corporation
> /usr/java/jdk-11.0.1
> 
> SWT v4922, gtk/3.22.30, zoom=100, dpi=109
> Linux v4.12.14-lp150.12.58-default, amd64 (64 bit)
> B1.9.0.0/4 az3
> 

I did completely remove 3DViews, restart, and re-added it but that didn't help.

The symptoms are pretty simple, I get nothing but a blank page.

I'm happy to give you more system info. etc as you need it to figure this out.

Thanks!

**Comment by parg** [comment]
Hmm, it works fine on kubuntu so it isn't a generic *nix issue. Unfortunately I don't have opensuse to test with - perhaps you can look in the debug_1.log / debug_2.log files in the BiglyBT logs directory to see if any failures are being logged?

**Comment by RegProctor** [comment]
This should have been closed a long time ago, sorry I missed doing that. The problem resurfaced but this time I can guess why. KDE just had a massive update to version 6 using Wayland instead of Xorg by default now and there's probably a few gremlins. I just updated my mesa-libGUI to make sure I had the latest as that didn't seemed to be part of that massive update.

From the help window:

```
Java 11.0.23 (64 bit)
  Oracle Corporation
/usr/lib64/jvm/java-11-openjdk-11

SWT v4956r12, gtk/3.24.41, zoom=100, dpi=96
Linux v6.8.8-1-default, amd64 (64 bit)
B3.6.0.0/4 az3 en
```

I picked up your comment above and here's the error from debug_1.log:

```
[11:05:48] [stderr] DEBUG::Sat May 11 11:05:48 MST 2024::com.biglybt.core.util.ThreadPool::checkWarning::368:
[11:05:48] [stderr]   Thread pool 'Simple Timer' is full (busy=rcm.delay.init,delay:tcp:connect,delay:tcp:connect,delay:tcp:connect,delay:tcp:connect,delay:tcp:connect,delay:tcp:connect,delay:tcp:connect,delay:tcp:connect,delay:tcp:connect,delay:tcp:connect,delay:tcp:connect,delay:tcp:connect,delay:tcp:connect,delay:tcp:connect,delay:tcp:connect,delay:tcp:connect)
[11:05:48] [stderr]     ThreadPool::run::246, ThreadPool::run::213, Timer::runSupport::342, AERunnable::run::36, Thread::run::829
[11:06:01] [stderr] DEBUG::Sat May 11 11:06:01 MST 2024::com.biglybt.ui.swt.pifimpl.UISWTViewImpl::triggerEvent::330:
[11:06:01] [stderr]   ViewID=view3d.subtab.name; EventID=DS; data=[com.biglybt.pifimpl.local.download.DownloadImpl@4eda9730]
[11:06:01] [stderr]     BaseMdiEntry::triggerEvent::669, UISWTViewImpl::setDatasource::254, BaseMdiEntry::setDatasource::1113, TabbedMDI::setEntriesDataSource::1557, TableViewSWT_TabsCommon::triggerTabViewsDataSourceChanged::100, MyTorrentsSuperView$9::lambda$0::456, Utils::execSWTThread::1993, Utils::execSWTThread::2159, MyTorrentsSuperView$9::currentlySelectedContentChanged::451, SelectedContentManager::triggerSelectedContentListeners::151, SelectedContentManager::changeCurrentlySelectedContent::86, MyTorrentsView::updateSelectedContent::1923, MyTorrentsView::updateSelectedContent::1896, MyTorrentsView::selectionChanged::1840, TableViewImpl::triggerSelectionChangeListeners::361, TableViewImpl::setSelectedRows::2633, TableViewImpl::setSelectedRows::2547, TableViewPainted::setSelectedRows::2938, TableViewImpl::setSelectedRows::2682, TableViewPainted$1::mouseUp::325, TableViewSWT_Common::mouseUp::204, TypedListener::handleEvent::224, EventTable::sendEvent::89, Display::sendEvent::5810, Widget::sendEvent::1529, Display::runDeferredEvents::5020, Display::readAndDispatch::4472, SWTThread::<init>::526, SWTThread::createInstance::58, Initializer::<init>::183, UI::takeMainThread::162, Main::main::247, NativeMethodAccessorImpl::invoke0::-2, NativeMethodAccessorImpl::invoke::62, DelegatingMethodAccessorImpl::invoke::43, Method::invoke::566, Launcher$1::run::48, Thread::run::829
[11:06:01] [stderr] java.lang.NullPointerException
[11:06:01] [stderr]     at com.aelitis.azureus.plugins.view3d.Panel3D.setDataSource(Panel3D.java:291)
[11:06:01] [stderr]     at com.aelitis.azureus.plugins.view3d.Plugin3D$ViewListener.eventOccurred(Plugin3D.java:268)
[11:06:01] [stderr]     at com.biglybt.ui.swt.pifimpl.UISWTViewImpl.triggerBooleanEvent(UISWTViewImpl.java:462)
[11:06:01] [stderr]     at com.biglybt.ui.swt.pifimpl.UISWTViewImpl.triggerEvent(UISWTViewImpl.java:330)
[11:06:01] [stderr]     at com.biglybt.ui.swt.mdi.BaseMdiEntry.triggerEvent(BaseMdiEntry.java:669)
[11:06:01] [stderr]     at com.biglybt.ui.swt.pifimpl.UISWTViewImpl.setDatasource(UISWTViewImpl.java:254)
[11:06:01] [stderr]     at com.biglybt.ui.swt.mdi.BaseMdiEntry.setDatasource(BaseMdiEntry.java:1113)
[11:06:01] [stderr]     at com.biglybt.ui.swt.mdi.TabbedMDI.setEntriesDataSource(TabbedMDI.java:1557)
[11:06:01] [stderr]     at com.biglybt.ui.swt.views.table.impl.TableViewSWT_TabsCommon.triggerTabViewsDataSourceChanged(TableViewSWT_TabsCommon.java:100)
[11:06:01] [stderr]     at com.biglybt.ui.swt.views.MyTorrentsSuperView$9.lambda$0(MyTorrentsSuperView.java:456)
[11:06:01] [stderr]     at com.biglybt.ui.swt.Utils.execSWTThread(Utils.java:1993)
[11:06:01] [stderr]     at com.biglybt.ui.swt.Utils.execSWTThread(Utils.java:2159)
[11:06:01] [stderr]     at com.biglybt.ui.swt.views.MyTorrentsSuperView$9.currentlySelectedContentChanged(MyTorrentsSuperView.java:451)
[11:06:01] [stderr]     at com.biglybt.ui.selectedcontent.SelectedContentManager.triggerSelectedContentListeners(SelectedContentManager.java:151)
[11:06:01] [stderr]     at com.biglybt.ui.selectedcontent.SelectedContentManager.changeCurrentlySelectedContent(SelectedContentManager.java:86)
[11:06:01] [stderr]     at com.biglybt.ui.swt.views.MyTorrentsView.updateSelectedContent(MyTorrentsView.java:1923)
[11:06:01] [stderr]     at com.biglybt.ui.swt.views.MyTorrentsView.updateSelectedContent(MyTorrentsView.java:1896)
[11:06:01] [stderr]     at com.biglybt.ui.swt.views.MyTorrentsView.selectionChanged(MyTorrentsView.java:1840)
[11:06:01] [stderr]     at com.biglybt.ui.common.table.impl.TableViewImpl.triggerSelectionChangeListeners(TableViewImpl.java:361)
[11:06:01] [stderr]     at com.biglybt.ui.common.table.impl.TableViewImpl.setSelectedRows(TableViewImpl.java:2633)
[11:06:01] [stderr]     at com.biglybt.ui.common.table.impl.TableViewImpl.setSelectedRows(TableViewImpl.java:2547)
[11:06:01] [stderr]     at com.biglybt.ui.swt.views.table.painted.TableViewPainted.setSelectedRows(TableViewPainted.java:2938)
[11:06:01] [stderr]     at com.biglybt.ui.common.table.impl.TableViewImpl.setSelectedRows(TableViewImpl.java:2682)
[11:06:01] [stderr]     at com.biglybt.ui.swt.views.table.painted.TableViewPainted$1.mouseUp(TableViewPainted.java:325)
[11:06:01] [stderr]     at com.biglybt.ui.swt.views.table.impl.TableViewSWT_Common.mouseUp(TableViewSWT_Common.java:204)
[11:06:01] [stderr]     at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:224)
[11:06:01] [stderr]     at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
[11:06:01] [stderr]     at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5810)
[11:06:01] [stderr]     at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
[11:06:01] [stderr]     at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5020)
[11:06:01] [stderr]     at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4472)
[11:06:01] [stderr]     at com.biglybt.ui.swt.mainwindow.SWTThread.<init>(SWTThread.java:526)
[11:06:01] [stderr]     at com.biglybt.ui.swt.mainwindow.SWTThread.createInstance(SWTThread.java:58)
[11:06:01] [stderr]     at com.biglybt.ui.swt.Initializer.<init>(Initializer.java:183)
[11:06:01] [stderr]     at com.biglybt.ui.swt.UI.takeMainThread(UI.java:162)
[11:06:01] [stderr]     at com.biglybt.ui.Main.main(Main.java:247)
[11:06:01] [stderr]     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[11:06:01] [stderr]     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[11:06:01] [stderr]     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[11:06:01] [stderr]     at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[11:06:01] [stderr]     at com.biglybt.launcher.Launcher$1.run(Launcher.java:48)
[11:06:01] [stderr]     at java.base/java.lang.Thread.run(Thread.java:829)
[11:06:01] java.lang.NullPointerException
        at com.aelitis.azureus.plugins.view3d.Panel3D.setDataSource(Panel3D.java:291)
        at com.aelitis.azureus.plugins.view3d.Plugin3D$ViewListener.eventOccurred(Plugin3D.java:268)
        at com.biglybt.ui.swt.pifimpl.UISWTViewImpl.triggerBooleanEvent(UISWTViewImpl.java:462)
        at com.biglybt.ui.swt.pifimpl.UISWTViewImpl.triggerEvent(UISWTViewImpl.java:330)
        at com.biglybt.ui.swt.mdi.BaseMdiEntry.triggerEvent(BaseMdiEntry.java:669)
        at com.biglybt.ui.swt.pifimpl.UISWTViewImpl.setDatasource(UISWTViewImpl.java:254)
        at com.biglybt.ui.swt.mdi.BaseMdiEntry.setDatasource(BaseMdiEntry.java:1113)
        at com.biglybt.ui.swt.mdi.TabbedMDI.setEntriesDataSource(TabbedMDI.java:1557)
        at com.biglybt.ui.swt.views.table.impl.TableViewSWT_TabsCommon.triggerTabViewsDataSourceChanged(TableViewSWT_TabsCommon.java:100)
        at com.biglybt.ui.swt.views.MyTorrentsSuperView$9.lambda$0(MyTorrentsSuperView.java:456)
        at com.biglybt.ui.swt.Utils.execSWTThread(Utils.java:1993)
        at com.biglybt.ui.swt.Utils.execSWTThread(Utils.java:2159)
        at com.biglybt.ui.swt.views.MyTorrentsSuperView$9.currentlySelectedContentChanged(MyTorrentsSuperView.java:451)
        at com.biglybt.ui.selectedcontent.SelectedContentManager.triggerSelectedContentListeners(SelectedContentManager.java:151)
        at com.biglybt.ui.selectedcontent.SelectedContentManager.changeCurrentlySelectedContent(SelectedContentManager.java:86)
        at com.biglybt.ui.swt.views.MyTorrentsView.updateSelectedContent(MyTorrentsView.java:1923)
        at com.biglybt.ui.swt.views.MyTorrentsView.updateSelectedContent(MyTorrentsView.java:1896)
        at com.biglybt.ui.swt.views.MyTorrentsView.selectionChanged(MyTorrentsView.java:1840)
        at com.biglybt.ui.common.table.impl.TableViewImpl.triggerSelectionChangeListeners(TableViewImpl.java:361)
        at com.biglybt.ui.common.table.impl.TableViewImpl.setSelectedRows(TableViewImpl.java:2633)
        at com.biglybt.ui.common.table.impl.TableViewImpl.setSelectedRows(TableViewImpl.java:2547)
        at com.biglybt.ui.swt.views.table.painted.TableViewPainted.setSelectedRows(TableViewPainted.java:2938)
        at com.biglybt.ui.common.table.impl.TableViewImpl.setSelectedRows(TableViewImpl.java:2682)
        at com.biglybt.ui.swt.views.table.painted.TableViewPainted$1.mouseUp(TableViewPainted.java:325)
        at com.biglybt.ui.swt.views.table.impl.TableViewSWT_Common.mouseUp(TableViewSWT_Common.java:204)
        at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:224)
        at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
        at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5810)
        at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5020)
        at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4472)
        at com.biglybt.ui.swt.mainwindow.SWTThread.<init>(SWTThread.java:526)
        at com.biglybt.ui.swt.mainwindow.SWTThread.createInstance(SWTThread.java:58)
        at com.biglybt.ui.swt.Initializer.<init>(Initializer.java:183)
        at com.biglybt.ui.swt.UI.takeMainThread(UI.java:162)
        at com.biglybt.ui.Main.main(Main.java:247)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.biglybt.launcher.Launcher$1.run(Launcher.java:48)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by parg** [comment]
Unfortunately the 3DView is based on https://legacy.lwjgl.org/ - version 2 of the library and is already running the last version of that.

There are significant differences between v2 and v3, I spent some time trying to migrate it a while back and gave up :(

**Comment by RegProctor** [comment]
Ah, so this is something I'll just have to accept is gone, it's a very nice plugin, sorry to see it go. 

Is Java a language that I could install an older version along side the current version and then maybe I could point your plugin to use it... something like that?

**Comment by parg** [comment]
It still works fine on Windows, OSX and some other flavours of Linux (e.g. Kubuntu), although for how much longer who knows...

You could run BiglyBT in a VM I guess!
